COMPASS-1727: Remove onActivated subscription to onQueryChanged and fix npm link (#2)
* Typo

* Update npm run link-plugin script to add hadron-app

It's needed by the 'DeploymentAwareness.TextWriteButton' component.

Note: "npm run unlink-plugin" appears to have two issues for me:

1. COMPASS_HOME environment variable is not set via .profile or .bashrc, not sure why, workaround is to set it at the command line, e.g.
COMPASS_HOME='/Users/pzrq/Projects/compass' npm run link-plugin

2. `npm run unlink-plugin` does not completely unlink all dependencies (it does unlink the plugin from Compass, but not the plugin from its dependencies), according to "npm-link-check":

BEFORE
$ npm-link-check
/Users/pzrq/.nvm/versions/node/v7.4.0/lib/node_modules/npm-link-check/cmd.js:23
    throw new Error(header + '\n' + list.join('\n') + '\n');
    ^

Error: Some npm-link'ed packaged were found:
   - package react (at node_modules/react) is linked

    at log (/Users/pzrq/.nvm/versions/node/v7.4.0/lib/node_modules/npm-link-check/cmd.js:23:11)
    at process.<anonymous> (/Users/pzrq/.nvm/versions/node/v7.4.0/lib/node_modules/npm-link-check/cmd.js:35:21)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)

AFTER
$ npm-link-check
/Users/pzrq/.nvm/versions/node/v7.4.0/lib/node_modules/npm-link-check/cmd.js:23
    throw new Error(header + '\n' + list.join('\n') + '\n');
    ^

Error: Some npm-link'ed packaged were found:
   - package hadron-app (at node_modules/hadron-app) is linked
   - package react (at node_modules/react) is linked

    at log (/Users/pzrq/.nvm/versions/node/v7.4.0/lib/node_modules/npm-link-check/cmd.js:23:11)
    at process.<anonymous> (/Users/pzrq/.nvm/versions/node/v7.4.0/lib/node_modules/npm-link-check/cmd.js:35:21)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)

* Remove onQueryChanged listeners from onActivated

Stops onQueryChanged being called twice in Compass.